# Generated by Django 4.2.3 on 2023-09-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="complete",
            field=models.CharField(
                choices=[("True", "True"), ("False", "False")], max_length=100
            ),
        ),
    ]
