# Generated by Django 4.2.3 on 2023-09-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_task_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
